name: Merge Request Checks

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - DEV

jobs:
  merge_request_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create JSON File
        run: |
          echo '{
            "port" : "${{ secrets.PORT }}",
            "token": "${{ secrets.TOKEN }}",
            "email": "cour@toujours@email",
            "bdd": {
              "user": "postgres",
              "host": "localhost",
              "database": "paye_ton_kawa",
              "password": "example",
              "port": 5434
            },
            "gmail": {
              "email": "payetonkawaepsi@gmail.com",
              "clientId": "555722656717-k88e6nvai6vgp987mbaps2bp70m4m187.apps.googleusercontent.com",
              "clientSecret": "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",
              "accessToken": "ya29.a0AbVbY6NzHHBRFo31IbfUzy_YA2Mek4Ja6TN96ad_UgqV1A_CvW2VXE_nwtt2rDHPGczX0xgQ8zUGYZ_uZKVpA4bOdKwCE9O5FiAFnq9k_JiVA3ThHeJpo9B_K-Dwcn950p-cEA-YlLdOFN7kiCnp1NPsdwcnaCgYKAdcSARASFQFWKvPlmT0izGZB8yqO-6EzPlB0Ww0163",
              "refreshToken": "1//04Kqp3effUzWUCgYIARAAGAQSNwF-L9IrV0pFxulPNYVs2xOQ6rOEPgyd90IHGrm0K4fwP_KTK4rfgShVdl9XNhYaGKquzJrumws"
            }
          }' > client-env.json


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Coverage
        run: npm test -- --detectOpenHandles --coverage

      - name: Check Test Coverage
        run: |
          coverage_threshold=$(node -p "require('./coverage/coverage-summary.json').total.lines.pct")
          if (( $(echo "$coverage_threshold < 100" | bc -l) )); then
            echo "Test coverage is less than 100%. Blocking merge request."
            exit 1
          fi

      - name: Build Application
        run: npm run build

      - name: Block Merge Request if Tests Failed or Coverage < 100%
        run: |
          if [[ ${{ job.status }} != "success" ]]; then
            echo "Tests failed. Blocking merge request."
            exit 1
          fi

      - name: Approve Merge Request
        if: success()
        run: echo "Merge request checks passed. Ready for merge."
